[theme]
primaryColor = "#1375f0"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#111827"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
